GET  http://localhost:3000/cursos HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

{
    "nome": ".Net"
}

###

PUT http://localhost:3000/cursos/1 HTTP/1.1
content-type: application/json

{
    "nome": "Angular 11"
}

###

DELETE  http://localhost:3000/cursos/3 HTTP/1.1
content-type: application/json
